name: Build Releases

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_windows.txt
        pip install pyinstaller
    
    - name: Build Windows executable
      run: |
        python build_windows.py
    
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v3
      with:
        name: UZAYTEK_HRMA_Windows
        path: dist/UZAYTEK_HRMA_Distribution/

  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build macOS application
      run: |
        python build_macos.py
    
    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v3
      with:
        name: UZAYTEK_HRMA_macOS
        path: |
          dist/UZAYTEK HRMA.app/
          UZAYTEK_HRMA_Installer.dmg

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build Linux executable
      run: |
        python build_linux.py
    
    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v3
      with:
        name: UZAYTEK_HRMA_Linux
        path: dist/UZAYTEK_HRMA_Linux/

  create-release:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
    
    - name: Create release packages
      run: |
        # Create Windows ZIP
        cd UZAYTEK_HRMA_Windows
        zip -r ../UZAYTEK_HRMA_Windows.zip *
        cd ..
        
        # Create macOS ZIP
        cd UZAYTEK_HRMA_macOS
        zip -r ../UZAYTEK_HRMA_macOS.zip *
        cd ..
        
        # Create Linux TAR.GZ
        cd UZAYTEK_HRMA_Linux
        tar -czf ../UZAYTEK_HRMA_Linux.tar.gz *
        cd ..
    
    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./UZAYTEK_HRMA_Windows.zip
        asset_name: UZAYTEK_HRMA_Windows.zip
        asset_content_type: application/zip
    
    - name: Upload macOS release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./UZAYTEK_HRMA_macOS.zip
        asset_name: UZAYTEK_HRMA_macOS.zip
        asset_content_type: application/zip
    
    - name: Upload Linux release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./UZAYTEK_HRMA_Linux.tar.gz
        asset_name: UZAYTEK_HRMA_Linux.tar.gz
        asset_content_type: application/gzip